local k = vim.keymap.set
local code = require("vscode")

k({ "n", "x", "i" }, "<C-d>", function()
	code.with_insert(function()
		code.action("editor.action.addSelectionToNextFindMatch")
	end)
end)

k("n", "R", function()
	code.action("editor.action.rename")
end, { silent = true })
k("n", "S", function()
	code.action("workbench.action.gotoSymbol")
end, { silent = true })
k("n", "gr", function()
	code.action("references-view.findReferences")
end, { silent = true })
k("n", "<leader>ca", function()
	code.action("editor.action.quickFix")
end, { silent = true })
k("n", ">", function()
	code.action("editor.action.indentLines")
end, { silent = true })
k("n", "<", function()
	code.action("editor.action.outdentLines")
end, { silent = true })
k("n", "<leader>s", function()
	code.action("workbench.action.files.save")
end, { silent = true })

-- GIT
k("n", "<leader>gs", function()
	code.action("git.checkout")
end, { silent = true })
k("n", "<leader>gp", function()
	code.action("git.pull")
end, { silent = true })
k("n", "<leader>gP", function()
	code.action("git.push")
end, { silent = true })
k("n", "<leader>gR", function()
	code.action("git.cleanAll")
end, { silent = true })
k("n", "<leader>gd", function()
	code.action("git.deleteBranch")
end, { silent = true })
k("n", "<leader>gb", function()
	code.action("git.blame.toggleEditorDecoration")
end, { silent = true })
k("n", "<leader>gc", function()
	code.action("git.commit")
end, { silent = true })
k("n", "<leader>gm", function()
	code.action("git.merge")
end, { silent = true })

-- UI
k("n", "<C-j>", function()
	code.action("workbench.action.togglePanel")
end, { silent = true })
k("n", "<C-b>", function()
	code.action("workbench.action.toggleSidebarVisibility")
end, { silent = true })
k("n", "<leader>wo", function()
	code.action("workbench.action.closeOtherEditors")
end, { silent = true })
k("n", "<leader>wO", function()
	code.action("workbench.action.closeEditorsInOtherGroups")
end, { silent = true })
k("n", "<leader>uc", function()
	code.action("workbench.action.toggleCenteredLayout")
end, { silent = true })
k("n", "<leader>us", function()
	code.action("workbench.action.toggleStatusbarVisibility")
end, { silent = true })
k("n", "<leader>ua", function()
	code.action("workbench.action.toggleActivityBarVisibility")
end, { silent = true })
k("n", "<leader><Right>", function()
	code.action("workbench.action.moveEditorToNextGroup")
end, { silent = true })
k("n", "<leader><Left>", function()
	code.action("workbench.action.moveEditorToPreviousGroup")
end, { silent = true })

-- NAVIGATION
k("n", "[e", function()
	code.action("editor.action.marker.prev")
end, { silent = true })
k("n", "]e", function()
	code.action("editor.action.marker.next")
end, { silent = true })

-- TESTING
k("n", "<leader>tt", function()
	code.action("extension.runJestFile")
end, { silent = true })
k("n", "<leader>tr", function()
	code.action("extension.runJest")
end, { silent = true })
k("n", "<leader>tc", function()
	code.action("extension.runJestFileWithCoverage")
end, { silent = true })
