-- { src = "https://github.com/catppuccin/nvim" },
return {
	"catppuccin/nvim",
	name = "catppuccin",
	lazy = false,
	priority = 1000,
	opts = {
		float = { transparent = true },
		transparent_background = true,
		no_italic = true,
		lsp_styles = {
			underlines = {
				errors = { "undercurl" },
				hints = { "undercurl" },
				warnings = { "undercurl" },
				information = { "undercurl" },
				ok = { "undercurl" },
			},
			inlay_hints = {
				background = true,
			},
		},
		integrations = {
			blink_cmp = true,
			flash = true,
			gitsigns = true,
			headlines = true,
			lsp_trouble = true,
			markdown = true,
			mason = true,
			neotest = true,
			noice = true,
			semantic_tokens = true,
			snacks = true,
			treesitter = true,
			treesitter_context = true,
		},
		custom_highlights = function(colors)
			return {
				CursorLine = { bg = colors.none },
				DiagnosticUnderlineHint = { sp = colors.red, undercurl = true },
				["@variable.builtin"] = { fg = colors.peach },
			}
		end,
		color_overrides = {
			all = {
				rosewater = "#8ccf7e",
				flamingo = "#a6e3a1",
				pink = "#9399b2",
				mauve = "#A0C399",
				red = "#ef7e7e",
				maroon = "#B8D2B3",
				peach = "#D0E1CC",
				yellow = "#f9e2af",
				green = "#a6e3a1",
				teal = "#71BAF2",
				sky = "#89dceb",
				sapphire = "#74c7ec",
				-- blue = "#9399b2",
				blue = "#D0F1DC",
				lavender = "#a6adc8",
				text = "#ffffff",
				subtext1 = "#bac2de",
				subtext0 = "#a6adc8",
				overlay2 = "#9399b2",
				overlay1 = "#7f849c",
				overlay0 = "#6c7086",
				surface2 = "#585b70",
				surface1 = "#45475a",
				surface0 = "#313244",
				base = "#141b1e",
				mantle = "#181825",
				crust = "#11111b",
			},
		},
	},
}
